CREATE TABLE userTable (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
login VARCHAR(30) NOT NULL,
pass VARCHAR(30) NOT NULL,
role VARCHAR(30)
) 


CREATE TABLE files (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
location VARCHAR(255),
login VARCHAR(30) NOT NULL,
);